n = int(input('Digite um número: '))
print('{:=^20}'.format('='))
print('{:5} * 1 = {}'.format(n,n*1))
print('{:5} * 2 = {}'.format(n,n*2))
print('{:5} * 3 = {}'.format(n,n*3))
print('{:5} * 4 = {}'.format(n,n*4))
print('{:5} * 5 = {}'.format(n,n*5))
print('{:5} * 6 = {}'.format(n,n*6))
print('{:5} * 7 = {}'.format(n,n*7))
print('{:5} * 8 = {}'.format(n,n*8))
print('{:5} * 9 = {}'.format(n,n*9))
print('{:5} * 10 = {}'.format(n,n*10))
print('{:=^20}'.format('='))